version: '3.1'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi4-homeassistant
    ports:
      - "8123:8123"
    volumes:
      - ./hass/config:/config:rw
      - ./hass/media:/media:rw
    environment:
      - TZ=Europe/Bucharest
    restart: always

